# thse are the initial values
DEFAULT_VALUES = {
    'Farmer_value': 0,
    'Farmer_maximum': 2147483647,
    'Farmer_minimum': 0,
    'Farmer_type': None,
    'Hunter_value': 0, 
    'Hunter_maximum': 2147483647,
    'Hunter_minimum': 0,
    'Hunter_type': None,
    'Baker_value': 0,
    'Baker_maximum': 2147483647,
    'Baker_minimum': 0,
    'Baker_type': None,
    'Butcher_value': 0,
    'Butcher_maximum': 2147483647,
    'Butcher_minimum': 0,
    'Butcher_type': None,
    'Logger_value': 0,
    'Logger_maximum': 2147483647,
    'Logger_minimum': 0,
    'Logger_type': None,
    'Builder_value': 0,
    'Builder_maximum': 2147483647,
    'Builder_minimum': 0,
    'Builder_type': None,
    'Available_value': 50,
    'Available_maximum': 2147483647,
    'Available_minimum': 0,
    'Available_type': None,
    'Population': 50,
    'Population_maximum': 2147483647,
    'Population_minimum': 0,
    'job_modifier' : 1,
    'week' : 1,
    'season' : 1,
    'year' : 1620,
    'Bread' : 4,
    'Cooked_Meat' : 4,
    'Vegetables' : 4,
    'Iron_Hoe' : 10,
    'Iron_Sickle' : 20,
    'Iron_Axe' : 10,
    'Rifle' : 5,
    'Bow' : 10,
    'Iron_Shovel' : 10,
    'Iron_Pickaxe' : 8,
    'Population' : 50,
    'RationP' : 100,
    'Health' : 85,
    'numberofFoods' : 4,
    'Strength' : 92.5,
    'Wheat' : 0,
    'Fur' : 0,
    'Raw_Meat' : 0,
    'Wild_Berries' : 0,
    'Clay' : 0,
    'Iron_Ore' : 0,
    'People' : 0,
    'Bricks' : 0,
    'Iron' : 0,
    'Anvil' : 0,
    'Planted' : 0,
    'Wood' : 20,
    'Log_Cabin' : 0,
    'Town_Hall' : 0,
    'Clay_Pit' : 0,
    'Mine' : 0,
    'Kiln' : 0,
    'Forge' : 0,
    'Tool_Shop' : 0,
    'Clay_Pit_Workers' : 0,
    'Clay_Pit_Workers_Max' : 0,
    'Mine_Workers' : 0,
    'Mine_Workers_Max' : 0,
    'Kiln_Workers' : 0,
    'Kiln_Workers_Max' : 0,
    'Forge_Workers' : 0,
    'Forge_Workers_Max' : 0,
    'building_queue' : "",
    'currently_building_queue' : "",
    'weekly_build_power' : 0,
    'buildings_to_add' : "",
    'SupplyTime' : -1,
    'SupplyShipsGiven' : 0,
    'SupplyShipType' : 0

}